// export const API_URL = 'http://localhost:8080/api/'
export const API_URL = 'https://hporx-backend.herokuapp.com/api/'
export const GET_PRODUCTS = ''
export const IMAGE_URL = 'https://hporx-backend.herokuapp.com/uploads/'
export const BASE_URL = 'https://hporx-backend.herokuapp.com/api/'