const bt = {
    public: {
        en: "What is Beta ?",
        es: "¿Qué es Beta?"
    },
    humanity: {
        en: "There is no greater service than service to humanity...",
        es: "No hay mayor servicio que el servicio a la humanidad..."
    },
    about_Public: {
        en: "About Public Beta",
        es: "Acerca de la versión beta pública"
    },
    intro: {
        en: "Beta is the second letter of the Greek alphabet. Originally, the term alpha test meant the first phase of testing in a software development process. In the HPO Rx React.js and React Native, cross-platform multi browser beta process of the software development applications developed exclusively for the global use of our clients based in 196 countries are members of the United Nations member states, a beta test is the first and second phase in oh validation of all the protocols submitted in our software development specifications (SRS) shared with our institutional stakeholders Bank Sabadell and The Financial Sector Advisory Center (FinSAC), World Bank who are the primary sponsors of the development of this global product for a 374 million global, commercial and individual clients of the Global cynical industry in service to plant base therapeutics. The software testing, in which the ßeta v1.1 sampling provided for your interaction, assessment, commentary and feedback, design for the aforementioned intended audience it's presented to you for your trial and collaborative feedback. You may explore all of its features and functionality, after which we encourage you to use the built-in feedback to reporting your experiences, pro or con, and your suggestions for improvement shared with our development operations (Devops) in Asia who Will use your feedback to improve the product based on your proactive suggestions submissions",
        es: "Beta es la segunda letra del alfabeto griego. Originalmente, el término prueba alfa significaba la primera fase de prueba en un proceso de desarrollo de software. En HPO Rx React.js y React Native, el proceso beta multiplataforma de múltiples navegadores de las aplicaciones de desarrollo de software desarrolladas exclusivamente para el uso global de nuestros clientes con sede en 196 países son miembros de los estados miembros de las Naciones Unidas, una prueba beta es la primera y segunda fase de validación de todos los protocolos presentados en nuestras especificaciones de desarrollo de software (SRS) compartidas con nuestros grupos de interés institucionales Bank Sabadell y The Financial Sector Advisory Center (FinSAC), Banco Mundial, que son los principales patrocinadores del desarrollo de este global producto para 374 millones de clientes globales, comerciales e individuales de la industria cínica global al servicio de la terapia a base de plantas. Las pruebas de software, en las que el muestreo de ßeta v1.1 se proporcionó para su interacción, evaluación, comentario y retroalimentación, el diseño para la audiencia prevista antes mencionada se le presenta para su prueba y retroalimentación colaborativa. Puede explorar todas sus características y funcionalidades, después de lo cual lo alentamos a que use los comentarios integrados para informar sus experiencias, a favor o en contra, y sus sugerencias de mejora compartidas con nuestras operaciones de desarrollo (Devops) en Asia que usarán su comentarios para mejorar el producto en función de sus sugerencias proactivas"
    },
    general: {
        en: "About ßeta and General Release Software",
        es: "Acerca de ßeta y el software de versión general"
    },
    general_release: {
        en: "A General Release Candidate (GA) In the software release life cycle, general availability (GA) refers to the marketing phase when all commercialization activities pertaining to the software product have been completed, and it is available for purchase.   A Release Candidate(RC) is a pre- release version of the software that is being prepared for its final product release(in the RC phase) to the public.This is sometimes referred to as “Controlled Availability”. Rational Team Concert(RTC) is an open, multi- platform team collaboration tool based on Jazz and Eclipse which provides developers with important functionality for agile application lifecycle management(ALM). Beta “Beta test” The Beta Test, Software testing and Beta testing Beta, named after the second letter of the Greek alphabet, is the software development phase following alpha.Software in the beta stage is also known as beta ware.[7] A beta phase generally begins when the software is feature complete but likely to contain several known or unknown bugs.[8] Software in the beta phase will generally have many more bugs in it than completed software and speed or performance issues, and may still cause crashes or data loss.The focus of beta testing is reducing impacts on users, often incorporating usability testing.The process of delivering a beta version to the users is called beta release and is typically the first time that the software is available outside the organization that developed it.Software beta releases can be either open or closed, depending on whether they are openly available or only available to a limited audience.Beta version software is often useful for demonstrations and previews within an organization and to prospective customers.Some developers refer to this stage as a preview, preview release, prototype, technical preview or technology preview(TP), [9] or early access. Beta testers are people who actively report issues with beta software.They are usually customers or representatives or prospective customers of the organization that develops the software.Beta testers tend to volunteer their services free of charge but often receive versions of the product they test, discounts on the release version, or other incentives.Perpetual beta Some software is kept in so   called perpetual beta, where new features are continually added to the software without establishing a final stable release.As the Internet has facilitated rapid and inexpensive distribution of software, companies have begun to take a looser approach to use of the word beta.",
        es: "Una versión candidata general (GA) En el ciclo de vida de la versión de software, la disponibilidad general (GA) se refiere a la fase de marketing cuando se han completado todas las actividades de comercialización relacionadas con el producto de software y está disponible para su compra. Un Release Candidate (RC) es una versión previa al lanzamiento del software que se está preparando para el lanzamiento del producto final (en la fase RC) al público. Esto a veces se denomina Disponibilidad controlada. Rational Team Concert (RTC) es una herramienta abierta de colaboración en equipo multiplataforma basada en Jazz y Eclipse que proporciona a los desarrolladores una funcionalidad importante para la gestión ágil del ciclo de vida de las aplicaciones (ALM). Beta “Prueba Beta” La Prueba Beta, prueba de software y prueba Beta Beta, llamada así por la segunda letra del alfabeto griego, es la fase de desarrollo de software que sigue a alfa. El software en la etapa beta también se conoce como software beta.[7] Una fase beta generalmente comienza cuando el software está completo, pero es probable que contenga varios errores conocidos o desconocidos.[8] El software en la fase beta generalmente tendrá muchos más errores que el software completo y problemas de velocidad o rendimiento, y aún puede causar fallas o pérdida de datos. El enfoque de las pruebas beta es reducir los impactos en los usuarios, a menudo incorporando pruebas de usabilidad. El proceso de entregar una versión beta a los usuarios se denomina lanzamiento beta y suele ser la primera vez que el software está disponible fuera de la organización que lo desarrolló. Los lanzamientos beta del software pueden ser abiertos o cerrados, dependiendo de si están disponibles abiertamente o solo disponibles para una audiencia limitada. El software de la versión beta suele ser útil para demostraciones y vistas previas dentro de una organización y para clientes potenciales. Algunos desarrolladores se refieren a esta etapa como vista previa, lanzamiento de vista previa, prototipo, vista previa técnica o vista previa de tecnología (TP), [9] o acceso temprano. Los evaluadores beta son personas que informan activamente problemas con el software beta. Suelen ser clientes, representantes o posibles clientes de la organización que desarrolla el software. en la versión de lanzamiento u otros incentivos. Beta perpetua Parte del software se mantiene en la llamada beta perpetua, donde continuamente se agregan nuevas funciones al software sin establecer una versión estable final. Como Internet ha facilitado la distribución rápida y económica de software, las empresas han comenzado a adoptar un enfoque más flexible en el uso de la palabra beta."
    },
    part: {
        en: "What part do I play?",
        es: "¿Qué papel juego?"
    },
    multi: {
        en: "This product is a multi faceted, multidisciplined, multivendor retail, wholesale, distribution online cross-platform mobile app application created to be viewed on multiple screens such as Apple IOS, Apple iPad, Apple TV, and the entire android Legacy of hardware and software screens currently use for millions of individuals and corporations across the world. The product is designed for individuals who temperature, wholesale or retail plant-based and holistic Therapeutic medicines, supplements products proactive to health or the extension of human life. The HPO Rx platform affords any commercial manufacturer or individual vendor of any plant base therapeutics the ability to create an account on the platform and showcase their it's in services or any country audience anywhere on earth. Platform also of Ford's employment for individuals in need of work, with a desire to be self-reliant and self-sufficient and are self-starters who only need access to a mobile device and a local telephone directory to access the potential to make $10-$20,000 a month selling advertising space on the platform to any vendor who has a product in which there is a one to 1% to 0% volume Cannabis sativa cultivars any alternative holistic or therapeutic plant base product goods or services of culåçtivated wellness and any other natural product legally accessible within their market of country with a scientifically tested and validated product designed for human consumption and the extension of human life and a positive benefit to human health outcomes. When you enter the web auto you'll notice that it's deliberately unfinished we want your opinion and assessment of what you Believe should be added or improved to serve the public it was designed to support and deliver a positive outcome?",
        es: "Este producto es una aplicación móvil multiplataforma multifacética, multidisciplinar, multiproveedor, minorista, mayorista, de distribución en línea creada para ser vista en múltiples pantallas como Apple IOS, Apple iPad, Apple TV y todo el legado de Android de pantallas de hardware y software. utilizan actualmente para millones de individuos y corporaciones en todo el mundo. El producto está diseñado para personas que toman temperatura, venden al por mayor o al por menor medicamentos terapéuticos holísticos y a base de plantas, complementan productos proactivos para la salud o la prolongación de la vida humana. La plataforma HPO Rx ofrece a cualquier fabricante comercial o proveedor individual de cualquier tratamiento a base de plantas la capacidad de crear una cuenta en la plataforma y mostrar sus servicios a la audiencia de cualquier país en cualquier parte del mundo. Plataforma también de empleo de Ford para personas que necesitan trabajo, con el deseo de ser autosuficientes y autosuficientes y son emprendedores que solo necesitan acceso a un dispositivo móvil y un directorio telefónico local para acceder al potencial de hacer $ 10- $20,000 al mes vendiendo espacios publicitarios en la plataforma a cualquier proveedor que tenga un producto en el que haya un volumen de uno a 1% a 0% Cultivares de Cannabis sativa cualquier producto alternativo holístico o terapéutico a base de plantas bienes o servicios de bienestar cultivado y cualquier otro producto natural producto legalmente accesible dentro de su mercado de país con un producto científicamente probado y validado diseñado para el consumo humano y la extensión de la vida humana y un beneficio positivo para la salud humana. Cuando ingrese a la web automática, notará que está deliberadamente inacabada. Queremos su opinión y evaluación de lo que cree que se debe agregar o mejorar para servir al público. ¿Fue diseñado para respaldar y brindar un resultado positivo?"
    },
    reward: {
        en: "My reward?",
        es: "¿Mi recompensa?"
    },
    cybertruck: {
        en: "Your email address may be entered in our Tesla Cybertruck / Cyberlandr raffle, $150,000 value, in exchange for substantial constructive feedback specifically any feedback which augments the UI/UX and is nothing we have not already planned and documented in our Software Requirement Specification Document, if the level of feedback offered is substantially less, we will still send you a useful token of our esteem, one guaranteed to protect your privacy online!",
        es: "Su dirección de correo electrónico puede ingresarse en nuestra rifa Tesla Cybertruck / Cyberlandr, con un valor de $ 150,000, a cambio de comentarios constructivos sustanciales, específicamente cualquier comentario que aumente la UI / UX y no sea nada que no hayamos planeado y documentado en nuestro Documento de especificación de requisitos de software, si el nivel de comentarios ofrecidos es sustancialmente menor, aún así le enviaremos una muestra útil de nuestra estima, ¡uno garantizado para proteger su privacidad en línea!"
    },
    pain: {
        en: "There is no one who loves pain itself, who seeks after it and wants to have it,simply because it is pain.",
        es: "No hay quien ame el dolor mismo, que lo busque y quiera tenerlo, simplemente porque es dolor."
    },
    human: {
        en: "It is our human right to live within pain, help others do the same",
        es: "Es nuestro derecho humano vivir dentro del dolor, ayudar a otros a hacer lo mismo"
    },
}

export default bt